name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
      # Envoie de notification d'échec du tests
      - name: Notify if tests fail
        if: failure() # cette étape va seulement s'exécuter que si les tests échouent
        uses: dawidd6/action-send-mail@v3
        with:
          # Nous allons vonfigurer notre adresse e-mail a partir d'ici
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Échec des tests pour votre application Flask"
          body: "Les tests de l'application Flask ont échoué."
          to: "choukri.souleiman.mahamoud@gmail.com"
          from: "github-ChoukriSOULEIMAN@github.com"

  build:
    runs-on: ubuntu-latest
    needs: tests # Exécute cette tâche uniquement si "tests" passe
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t ChoukriSOULEIMAN/flaskapp .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_choukri34 }}
          password: ${{ secrets.DOCKER_choukri24 }}

      - name: Push Docker image to Docker Hub
        if: success() # cette étape ne s'exécute que si tous les jobs réussissent
        run: docker push ChoukriSOULEIMAN/flaskapp

      # Pousser l'image vers un registre Docker privé
      - name: Push Docker image to Private Registry
        if: success()
        env:
          DOCKER_REGISTRY: private-registry.com
        run: |
          docker tag ChoukriSOULEIMAN/flaskapp $DOCKER_REGISTRY/ChoukriSOULEIMAN/flaskapp
          echo ${{ secrets.PRIVATE_REGISTRY_PASSWORD }} | docker login $DOCKER_REGISTRY -u ${{ secrets.PRIVATE_REGISTRY_USERNAME }} --password-stdin
          docker push $DOCKER_REGISTRY/username/flaskapp
